name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Torch data (datasets/models)
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/torch
          key: ${{ runner.os }}-torch-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-torch-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # утилиты на всякий случай (если их нет в requirements.txt)
          pip install pre-commit mypy pytest pytest-cov

      - name: Pre-commit (lint + format) — skip if no config
        run: |
          if [ -f ".pre-commit-config.yaml" ]; then
            pre-commit run --all-files
          elif [ -f ".pre-commit-config.yml" ]; then
            mv .pre-commit-config.yml .pre-commit-config.yaml
            pre-commit run --all-files
          else
            echo "No .pre-commit-config.yaml found — skipping pre-commit step."
          fi

      - name: Type check (mypy)
        run: |
          # даём mypy видеть импорты вида "from src.*" без __init__.py
          export MYPYPATH=$PWD
          mypy scripts app tests --ignore-missing-imports --explicit-package-bases --python-version 3.10

      - name: Run tests
        env:
          # включаем src/ как namespace-package для pytest
          PYTHONPATH: ${{ github.workspace }}
          TORCH_HOME: ${{ runner.temp }}/torch
          PYTHONWARNINGS: ignore
        run: |
          pytest -q --maxfail=1 --disable-warnings
